version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      day: friday
      interval: "weekly"
      timezone: "Asia/Baghdad"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
